### ISSUE TITLE
Hi gang!  Agora would be incredible

### ISSUE THREAD

**Issue by smhk** [needle-mirror/com.unity.nuget.newtonsoft-json#1]
Howdy!

it would be incredible if you could mirror the agora.io as a package.

It's a huge nuisance it's only on the asset store. https://assetstore.unity.com/packages/tools/video/agora-video-sdk-for-unity-134502

BTW is there a Tip Jar?  (paypal)

Cheers, JP

**Comment by hybridherbst** [comment]
Hey @smhk , not quite the right place but thanks for the question :) 
For reference, we have a Discord with a Mirror channel for feature requests, ideas etc: https://discord.gg/CFZDp4b

Regarding your question, so far we only mirror packages from Unity's registry, because there the license kinda somewhat leaves that flexibility (the "Companion License"). For AssetStore and external tools that is less clear; we can't just upload someone's code/assets (even if free) from the AssetStore.

The ideal solution would be that Agora make their package releases publicly available on GitHub (https://github.com/AgoraIO); might be worth to drop them a mail and ask nicely!

**Comment by smhk** [comment]
@hybridherbst thank you so much, sorry about the "wrong channel" ! all understood, thanks!

mfg
